### ISSUE TITLE
reset.css

### ISSUE THREAD

**Issue by chadkeeven** [den-materials/design-and-css-challenge-lab#11]
What's the point of the reset.css file? It seems to make things harder if linked in HTML file. I had to manually do list-style for ul.

**Comment by ZebGirouard** [comment]
@chadkeeven , the main reason you use `reset.css` is because you need to support multiple browsers on multiple devices and you do not trust Chrome-for-Android, Safari-for-MacBook, and IE8 for Windows 10 to all work the way you want them to.  Yes, it is definitely a lot of work up-front and you often want to avoid it, but if you want complete control, it's the only way to go.
